version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - './docker/nginx:/etc/nginx/conf.d:cached'
      - './packages/frontend:/var/www/html:cached'
    ports:
      - '80:80'
    depends_on:
      - frontend
    links:
      - frontend

  frontend:
    container_name: frontend
    image: node:12
    command: >
      bash -c "npm i &&
      npx webpack-dev-server --hot --inline --config webpack/config.js"
    working_dir: /var/www/html
    volumes:
      - './packages/frontend:/var/www/html:cached'
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  backend:
    container_name: backend
    image: node:12
    command: bash -c "npm i && npm start"
    working_dir: /var/www/html
    volumes:
      - './packages/backend:/var/www/html:cached'
    ports:
      - '8000:8000'

  mysql:
    container_name: mysql
    image: 'mysql:5.6'
    volumes:
      - './docker/db:/docker-entrypoint-initdb.d'
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'
    tmpfs:
      - '/tmp:rw'
    environment:
      - MYSQL_DATABASE=todo_list
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no

volumes:
  db:
